apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    version: test
  name: apicontagem
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: apicontagem
  type: LoadBalancer