apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.14.0 (fa706f2)
  creationTimestamp: null
  labels:
    io.kompose.service: apicontagem
  name: apicontagem
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: apicontagem
    spec:
      containers:
      - env:
        - name: 'DOCKER_REGISTRY_SERVER_PASSWORD '
          value: ''
        - name: 'DOCKER_REGISTRY_SERVER_URL '
          value: ''
        - name: 'DOCKER_REGISTRY_SERVER_USERNAME '
          value: ''
        image: [azure-container-registry-name].azurecr.io/apicontagem:latest
        livenessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost/api/contador
          failureThreshold: 3
          periodSeconds: 90
          timeoutSeconds: 10
        name: apicontagem
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
