apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apicontagem-deployment
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: apicontagem
    spec:
      containers:
      - name: apicontagem
        image: w2registry.azurecr.io/apicontagem:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: apicontagemregistrykey