version: '3'

services:
  apicontagem:
    image: [azure-container-registry-name].azurecr.io/apicontagem:latest
    #build:
    #  context: ./
    #  dockerfile: Dockerfile
    container_name: apicontagem
    ports:
      - 80:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/contador"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    environment:
      - DOCKER_REGISTRY_SERVER_USERNAME = [azure-container-registry-name]
      - DOCKER_REGISTRY_SERVER_URL = [azure-container-registry-name].azurecr.io
      - DOCKER_REGISTRY_SERVER_PASSWORD = [password]
